name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Elm
        run: npm install -g elm

      - name: Create dist directory
        run: mkdir -p dist

      - name: Build project
        run: elm make src/Main.elm --optimize --output=dist/elm.js

      - name: Copy public files to dist
        run: |
          if [ -d "public" ]; then
            cp -r public/* dist/
          else
            echo "Public directory not found. Please create a public directory with index.html"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
